### ISSUE TITLE
Dataset and Model

### ISSUE THREAD

**Issue by hjs2027864933** [sher222/LeReT#2]
What a great work! Since generating data and training models are expensive, can you provide the generated dataset and trained model? I can't wait to experience it!

**Comment by sher222** [comment]
Hi @hjs2027864933, thanks for checking out LeReT! Unfortunately, the generated datasets and trained models are specific to the task at hand (Hotpot or Hover) and given the limited utility, we will not be releasing the datasets/models. For use on different tasks / applications, you do unfortunately need to generate the dataset and train the model yourself.
