### ISSUE TITLE
Colbert retrieving incorrect passages

### ISSUE THREAD

**Issue by java-abhinav07** [sher222/LeReT#3]
Thanks a lot for sharing your code. 

I am trying to reproduce your results as mentioned in the paper and am facing some issues as described below. Steps to reproduce are as follows:
1. Create collection.tsv from 2017 wikipedia abstracts
2. Download pretrained colbertv2 checkpoint from [https://downloads.cs.stanford.edu/nlp/data/colbert/colbertv2/colbertv2.0.tar.gz]
3. As per the readme, download colbertv2 index from ([https://huggingface.co/sher222/ColBERTv2-wiki2017-index/tree/main])
4. Update paths in colbertv2_local.py:
```
index_root = "/data/leret/"
index_name = "wiki17.nbits.local"
self.searcher = Searcher(index=index_name, index_root=index_root, checkpoint="/data/leret/colbertv2.0", collection="/data/leret/collection.tsv")
```
5. Run `python create_preference_dataset.py --model_name meta-llama/Meta-Llama-3-8B-Instruct --together_api_key YOUR_API_KEY --out_file /MYOUTFILE/LeReT_demo/ --num_threads 1 --cache_dir YOUR_CACHE_DIR`

The code starts execution but I consistently get Average metric value 0, and upon closer inspection I realized that the passages retrieved by colbert (local) were incoherent despite the input prompt being understandably correct. For example consider the instance below:

`Example({'question': 'Who directed the Korean movie Scandal Makers?'}) (input_keys={'question'})`

Colbert retrieved the following titles: `['Mpanda, Mpanda', 'Wim den Herder', 'Maciej Radziwiłł']` 
which are incorrect.

To verify if the problem was indeed with the retriever I tried the hosted colbertv2 model and got the correct reponses `Kang Hyeong-cheol, Scandal Makers, Scandal Makers`

```
colbertv2_wiki17_abstracts = dspy.ColBERTv2(url='http://20.102.90.50:2017/wiki17_abstracts')
colbertv2_wiki17_abstracts('Who directed the Korean movie Scandal Makers?', k=3) 
```

Additionally I also verified that the `collection.tsv` which I created has the exact same passages as the ones retrieved by the hosted colbert model. 

I suspect there is either a problem with the checkpoint I am using or something specific in the code. Kindly help me resolve this issue, I have been trying to do something similar and would love to reproduce your impressive results, thanks again!

**Comment by hjs2027864933** [comment]
Hey, bro. I'm also trying to reproduce this project recently. Let me talk about the differences with yours, maybe it will help you.
I got the collection.tsv file from the following link:
```
# Preprocessed Wikipedia Abstracts 2017 collection (1 GB compressed)
wget https://downloads.cs.stanford.edu/nlp/data/colbert/baleen/wiki.abstracts.2017.tar.gz
tar -xvzf wiki.abstracts.2017.tar.gz
```
Like you, I also used the local pretrained colbertv2.
I executed the code in sample_run.py to create the preference dataset.
I got the following result, and the value of ap does not seem to be 0:
```
defaultdict(<class 'int'>, {'em': 0.5, 'ap': 0.4404761904761904, 'count': 7})
```
Hope it can help you.

**Comment by sher222** [comment]
Hey @java-abhinav07, why are you having to download the checkpoint / collection.tsv file? I think that the index by itself (along with installing colbert-ai using pip) should be all you need.

**Comment by java-abhinav07** [comment]
Hi, thanks for your reply and apologies for the delay. 

The index directory has two files, namely, `metadata.json` and `plan.json` which has the path to colbert checkpoint and collection.tsv hard coded. I was getting an error whenever I initialized `Searcher` in `colbertv2_local.py` and had to change the paths there to make it work. Please find the traceback below:

metadata.json
```
"checkpoint": "\/iris\/u\/sherylh\/rl-rag\/dspy\/experiments\/ColBERT\/data\/colbertv2.0",
"collection": "\/iris\/u\/sherylh\/rl-rag\/dspy\/experiments\/ColBERT\/data\/wiki.abstracts.2017\/collection.tsv",
"queries": "\/future\/u\/okhattab\/data\/MSMARCO\/queries.train.tsv",
"index_name": "wiki17.nbits.local",
"overwrite": false,
"root": "\/iris\/u\/sherylh\/rl-rag\/dspy\/experiments\/ColBERT\/",
```

traceback:
```
File "/home/user/LeReT/customdspy/colbertv2_local.py", line 22, in __init__
    self.searcher = Searcher(index=index_name, index_root=index_root) #, checkpoint="/data/leret/colbertv2.0", collection="/data/leret/collection.tsv")
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/miniconda3/envs/LeReT/lib/python3.12/site-packages/colbert/searcher.py", line 38, in __init__
    self.collection = Collection.cast(collection or self.config.collection)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/miniconda3/envs/LeReT/lib/python3.12/site-packages/colbert/data/collection.py", line 89, in cast
    return cls(path=obj)
           ^^^^^^^^^^^^^
  File "/home/user/miniconda3/envs/LeReT/lib/python3.12/site-packages/colbert/data/collection.py", line 17, in __init__
    self.data = data or self._load_file(path)
                        ^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/miniconda3/envs/LeReT/lib/python3.12/site-packages/colbert/data/collection.py", line 33, in _load_file
    return self._load_tsv(path) if path.endswith('.tsv') else self._load_jsonl(path)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/user/miniconda3/envs/LeReT/lib/python3.12/site-packages/colbert/data/collection.py", line 36, in _load_tsv
    return load_collection(path)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/miniconda3/envs/LeReT/lib/python3.12/site-packages/colbert/evaluation/loaders.py", line 160, in load_collection
    with open(collection_path) as f:
         ^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/iris/u/sherylh/rl-rag/dspy/experiments/ColBERT/data/wiki.abstracts.2017/collection.tsv'
```

As a result, I simply added the collection, checkpoint arguments as Searcher arguments. Note that I also tried using one of the hf links (colbert-ir/colbertv2.0) as the checkpoint argument and faced the same issue.

**Comment by java-abhinav07** [comment]
> Hey, bro. I'm also trying to reproduce this project recently. Let me talk about the differences with yours, maybe it will help you. I got the collection.tsv file from the following link:
> 
> ```
> # Preprocessed Wikipedia Abstracts 2017 collection (1 GB compressed)
> wget https://downloads.cs.stanford.edu/nlp/data/colbert/baleen/wiki.abstracts.2017.tar.gz
> tar -xvzf wiki.abstracts.2017.tar.gz
> ```
> 
> Like you, I also used the local pretrained colbertv2. I executed the code in sample_run.py to create the preference dataset. I got the following result, and the value of ap does not seem to be 0:
> 
> ```
> defaultdict(<class 'int'>, {'em': 0.5, 'ap': 0.4404761904761904, 'count': 7})
> ```
> 
> Hope it can help you.

I tried this out and it seems to work! The collection.tsv I manually created from hotpotqa preprocessed dump is slightly different from the link you shared.

Thanks a lot for the suggestion!
